a=input("Enter your last name:")
b=input("Enter your first name:")
c=input("Enter your Roll number:")
d=input("Enter your marks of maths:")
x=input("Enter your marks of chemistry:")
y=input("Enter your marks of phycis:")
z=int(d)+int(x)+int(y)

print("Name\t\t\tRoll number\tTotal marks")
print("\n",a, b,"\t\t",c,"\t\t",z)